env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-13-0-release-amd64
      image: freebsd-12-0-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y autoconf automake gmake libtool
  script:
    - printenv && uname -a && ls -l && /bin/sh -x ./bin/setup.sh && cd build && env MAKE=gmake ../configure --enable-warnings && gmake && sudo gmake install && gmake test

