name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: resolve dependency
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install byacc
    - name: configure
      run: |
        sh bin/setup.sh
        ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
