name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: resolve dependency
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install byacc
    - name: configure
      run: |
        sh bin/setup.sh
        ls -l /bin/msgfmt
        which msgfmt
        cd build; sh -x ../configure
    - name: make
      run: cd build ; make
    - name: make check
      run: cd build ; make check
    - name: make distcheck
      run: cd build ; make distcheck
